# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: simenvg.github.io
email: your-email@domain.com
description: > # Don't know what I'm doing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://simenvg.github.io" # the base hostname & protocol for your site
twitter_username: dfsaf
github_username:  simenvg

# Build settings
markdown: kramdown
